name: msnAutoAfk
version: '${project.version}'
main: dev.msn.autoafk.AutoAfk
api-version: '1.21'
folia-supported: true
author: msn

commands:
  msnautoafk:
    description: Toggle auto AFK detection or reload configuration
    usage: /msnautoafk [reload|debug]
    aliases: [autoafk]
    permission: msnautoafk.use

permissions:
  msnautoafk.use:
    description: Allows the player to use auto AFK features
    default: op
  msnautoafk.reload:
    description: Allows the player to reload the plugin configuration
    default: op
  msnautoafk.debug:
    description: Allows the player to toggle debug messages
    default: op
  msnautoafk.updatenotify:
    description: Receive notifications about plugin updates
    default: op